# Generated by Django 5.0.7 on 2024-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0003_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
